name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        EnumerationStrategy: ["For", "Foreach", "Enumerator", "Range"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build src/One.More.Lib.For.Linq.sln --configuration Release

    - name: Test - ${{ matrix.EnumerationStrategy }}
      run: dotnet test src/One.More.Lib.For.Linq.Tests
      env:
        EnumerationStrategy: ${{ matrix.EnumerationStrategy }}